# -*- coding: utf-8 -*-
"""Практическая 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sExMWpYpgmRn62ROwau0arJOUgBkb-nV
"""

class Person:
  def __init__(self,n,s, q = 1):
    self.name = n
    self.surname = s
    self.skill = q
  def info(self):
      return "{} {}, {}".format(self.name, self.surname, self.skill)
  def __del__(self):
    print("До свидания, мистер {} {}".format(self.name, self.surname))

worker = Person("И", "Котов", 3)
print(worker.info())
helper = Person("Д", "Мишев", 4)
print(helper.info())
maker = Person("О", "Рисов", 5)      
print(maker.info())
del helper
print("Конец программы")
input()

class Student:
  def __init__(self, s,h,n,g,u, group = "АДЭУ"):
      self.surname = s
      self.name = h
      self.grade = n
      self.gender = g
      self.univer = u
      self.group = group

  def mark(self):
      return n

  def display(self):
      return self.name, self.surname,self.univer, self.group, self.gender, self.grade  

  def __del__(self):
    if self.grade == n[2]:
        print("Отчислен студент", self.surname, self.name)

n ={2:'Задолжник', 4:'Ударник', 5:'Отличник'}
st1 = Student("Кролов", "Юрий", n[5], "М", "МГПУ") 
st2 = Student("Кравец", "Дарья", n[5], "Ж", "МГПУ")

print(st1.display())
print(st2.display())
if st1.grade == st2.grade:
  print("!МОЛОДЦЫ!")
del st1
del st2